name: Test Project

on:
  push:
    branches:
  workflow_dispatch:

jobs:
  test-project:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: go version

      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: make test
