name: Test Project

on:
  push:
    branches:
  workflow_dispatch:

jobs:
  test-project:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: make test